[31mERROR: Received the following error from Worker-0: ResetNeeded: Cannot call env.step() before calling env.reset()
[31mERROR: Shutting down Worker-0.
[31mERROR: Raising the last exception back to the main process.
Traceback (most recent call last):
  File "C:\Users\TYLER\Documents\GitHub\BeyondTheRainbow\main.py", line 150, in <module>
    eval_observation_, eval_reward, eval_done_, eval_trun_, eval_info = eval_env.step(action)
                                                                        ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\TYLER\AppData\Local\Programs\Python\Python311\Lib\site-packages\gymnasium\vector\vector_env.py", line 204, in step
    return self.step_wait()
           ^^^^^^^^^^^^^^^^
  File "C:\Users\TYLER\AppData\Local\Programs\Python\Python311\Lib\site-packages\gymnasium\vector\async_vector_env.py", line 333, in step_wait
    self._raise_if_errors(successes)
  File "C:\Users\TYLER\AppData\Local\Programs\Python\Python311\Lib\site-packages\gymnasium\vector\async_vector_env.py", line 544, in _raise_if_errors
    raise exctype(value)
gymnasium.error.ResetNeeded: Cannot call env.step() before calling env.reset()